travelproject/credential/urls.py
from . import views
from django.urls import path
app_name="credential"
urlpatterns=[
    path("registration/",views.registration,name='registration'),
    path("login/",views.login,name="login"),
    path('logout/',views.logout,name='logout')

]

travelproject/travelapp/urls.py
from . import views
from django.urls import path


urlpatterns=[
    path("",views.demo,name='index'),
    # path("add/",views.addition,name="addition"),

]

travelproject/travelproject/urls.py
from django.contrib import admin
from django.urls import path,include

from travelproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("travelapp.urls")),
    path('cred/',include("credential.urls")),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

travelproject/credential/models.py
from django.db import models

# Create your models here.

travelproject/travelapp/models.py
from django.db import models

class Place(models.Model):
    name=models.CharField(max_length=250)
    img=models.ImageField(upload_to='pics')
    desc=models.TextField()

travelproject/credential/views.py
from django.contrib import messages, auth

from django.contrib.auth.models import User

from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method=="POST":
        uname = request.POST['user name']
        password = request.POST['password']
        user=auth.authenticate(username=uname,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect("/")
        else:
            messages.info(request,"invalid credentials")
            return redirect('login')
    return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def registration(request):
    if request.method=="POST":
        uname=request.POST['user name']
        fname = request.POST['first name']
        lname = request.POST['last name']
        email = request.POST['email']
        password = request.POST['password']
        password1 = request.POST['password1']
        if password==password1:
            if User.objects.filter(username=uname).exists():
                messages.info(request,"user name taken")
                return redirect('registration')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email taken")
            else:
                user=User.objects.create_user(username=uname,first_name=fname,last_name=lname,email=email,password=password)
                user.save()
                return redirect('login')

        else:
             messages.info(request,"password not matching")
             return redirect("registration")
        return redirect('/')
    return render(request, "register.html", )

travelproject/travelapp/views.py
from django.shortcuts import render

# def demo(request):
#
#     return render(request,"demo.html", )
# def addition(request):
#     x=int(request.GET["num1"])
#     y=int(request.GET["num2"])
#     res=x+y
#     sub=x-y
#     mul=x*y
#     div=x/y
#     return render(request,"add.html",{"result":res,"substraction":sub,"multiplication":mul,"division":div})

def demo(request):

    return render(request,"index.html", )

travelproject/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
result is{{result}} <br>
substraction{{substraction}}<br>
multiplication{{multiplication}}<br>
division{{division}}

</body>
</html>

travelproject/templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>demo</title>
</head>
<body>
hello {{obj}}
<form action="/add/" method="get">
    <input type="text" name="num1" placeholder="enter no 1">
    <input type="text" name="num2" placeholder="enter no 2">
    <input type="submit">
</form>
</body>
</html>

travelproject/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MY DETAILS</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="{% static 'https://fonts.googleapis.com' %}">
<link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}" crossorigin>
<link href={"https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap " rel="stylesheet">

<link rel="stylesheet" href="{% static 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css' %}" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
    <header>
    <section class="navsection" >
        <div class="logo">
            <h1>Muhammed shahin technical</h1>
        </div>
        <nav >

            <!-- <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fa-solid fa-bars" ></i>
            </label> -->



           
             <a href="#">Home</a>
             <a href="#" >courses</a>
            {% if user.is_authenticated %}
            hello {{user.username}}
            <a href=" {% url 'credential:logout' %}">logout</a>
            {% else %}
             <a href="{% url 'credential:registration' %}">register</a>
             <a href="{% url 'credential:login' %}">login</a>
            {% endif %}

        
            
        
        </nav>


        <section></section>
    </section>
    <main id="m">
        <div class="leftside">
            <h3>hello</h3>
            <h1>iam muhammed shahin kc</h1>
            <h2>web developer</h2>

            <a class="btn1" href="https://docs.google.com/forms/d/e/1FAIpQLSdbSsi2h_akT_7NeLE6boTuy7fYh-bpoMENImL8CZuTk1DTCw/viewform?usp=sf_link" >Hire me</a>



             <a class="btn2" href="tel:+971507286676">Contact Me</a>

        </div>
        <div class="rightside">
            <img src="{% static 'image/cartoon.webp' %}" alt="">

        </div>
    </main>
</header>



<!-- -----------course-------- -->

<section class="course" id="c">
    <h3>
        My internships are.....
    </h3>
    
    <div class="row">
        <div class="course-col">
            <h3>python web development </h3>
            <p>Familiar with HTML, JavaScript and Bootstrap <br>
                Familiar with OOPs <br>
                Knowledge of SQL <br> 
                project experience in web development <br>
                Knowledge of Python, Angular, and Django <br>
                Familiar with GIT
                </p>

        </div>
        <div class="course-col">
            <h3>ccna / mcse</h3>
            <p>system administration <br>
            routing and switching <br>
        networking and hardwaring <br>server installation <br>firewall configuration</p>

        </div>
        <div class="course-col">
            <h3>tally / g-basic</h3>
            <p>purchace <br>sale <br>purchace return <br>sales return <br>word,excel,power point</p>

        </div>
        
    </div>
</section>


<!-- --------gallery--------- -->
<section class="campus" id="g">
    <h1>MY Pictures</h1>
   
    <div class="row">
        <div class="campus-col">
            <img src="{%static 'image/old.jpg ' %}" >
            <div class="layer">
                <h3>Old Photo</h3>
            </div>

        </div>

        <div class="campus-col">
            <img class="s" src=" {%static 'image/cv.png' %}" >
            <div class="layer">
                <h3>Cv</h3>
            </div>

        </div>


        <div class="campus-col">
            <img class="s" src="{%static 'image/new.jpg' %}" >
            <div class="layer">
                <h3>New Photo</h3>
            </div>

        </div>
       



</section>


<!-- ------about-------- -->
<div class="container">

    <section class="footer" id="f">
        <h4>About Me</h4>
        <p>Dedicated and Passionate Computer Science graduate with a strong foundation in Software
            Development . Strong analytical and problem solving skills and ability to learn new technologies
            quickly. Self motivated and passionate about Software Development, eager to start my career in
            this field and make an impact.
            </p>
        <div class="icon" id="ic">
            
            
            <a class="fa fa-facebook"  href="https://www.facebook.com/"></a>
            <a class="fa fa-twitter" href="https://twitter.com/home"></a>
            <a class="fa fa-instagram" href="https://www.instagram.com/"></a>
            <a class="fa fa-linkedin" href="https://www.linkedin.com/feed/"></a>
           

        </div>
        <p>YOU CAN CONTACT-0507286676,Al nahda,Dubai,Uae</p>
        <p>Developed by shahin</p>

    </section>
</div>



</body>
</html>

travelproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}

    <input type="text" name="user name" placeholder="enter ur name"> <br>
    <input type="password" name="password" placeholder="enter ur password">
     <input type="submit">
</form>
</body>
</html>

travelproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Registration form</h1>
<form action=" /registration/" method="post" >
    {% csrf_token %}
    <input type="text" name="user name" placeholder="enter ur name"> <br>
    <input type="text" name="first name" placeholder="enter ur first name"> <br>
        <input type="text" name="last name" placeholder="enter ur last name"> <br>
        <input type="email" name="email" placeholder="enter ur email"> <br>
        <input type="password" name="password" placeholder="enter ur password"> <br>
    <input type="password" name="password1" placeholder="confirm ur password"> <br>
    <input type="submit">

</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>

</html>